# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/benedikt/UE_5.1.1
GAMEPROJECTFILE =/home/benedikt/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject

TARGETS = \
	CryptRaider-Linux-DebugGame  \
	CryptRaider-Linux-Shipping  \
	CryptRaider \
	CryptRaiderEditor-Linux-DebugGame  \
	CryptRaiderEditor-Linux-Shipping  \
	CryptRaiderEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CryptRaiderEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CryptRaiderEditor-Linux-Debug


CryptRaider-Linux-DebugGame:
	 $(PROJECTBUILD) CryptRaider Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CryptRaider-Linux-Shipping:
	 $(PROJECTBUILD) CryptRaider Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CryptRaider:
	 $(PROJECTBUILD) CryptRaider Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CryptRaiderEditor-Linux-DebugGame:
	 $(PROJECTBUILD) CryptRaiderEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CryptRaiderEditor-Linux-Shipping:
	 $(PROJECTBUILD) CryptRaiderEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CryptRaiderEditor:
	 $(PROJECTBUILD) CryptRaiderEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
